/* automatically generated by rust-bindgen 0.70.1 */

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::std::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::std::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::std::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::std::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::std::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub const __GENTOO_NOT_FREESTANDING: u32 = 1;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __BITS_PER_LONG: u32 = 64;
pub const _IOC_NRBITS: u32 = 8;
pub const _IOC_TYPEBITS: u32 = 8;
pub const _IOC_SIZEBITS: u32 = 14;
pub const _IOC_DIRBITS: u32 = 2;
pub const _IOC_NRMASK: u32 = 255;
pub const _IOC_TYPEMASK: u32 = 255;
pub const _IOC_SIZEMASK: u32 = 16383;
pub const _IOC_DIRMASK: u32 = 3;
pub const _IOC_NRSHIFT: u32 = 0;
pub const _IOC_TYPESHIFT: u32 = 8;
pub const _IOC_SIZESHIFT: u32 = 16;
pub const _IOC_DIRSHIFT: u32 = 30;
pub const _IOC_NONE: u32 = 0;
pub const _IOC_WRITE: u32 = 1;
pub const _IOC_READ: u32 = 2;
pub const IOC_IN: u32 = 1073741824;
pub const IOC_OUT: u32 = 2147483648;
pub const IOC_INOUT: u32 = 3221225472;
pub const IOCSIZE_MASK: u32 = 1073676288;
pub const IOCSIZE_SHIFT: u32 = 16;
pub const BTRFS_IOCTL_MAGIC: u32 = 148;
pub const BTRFS_VOL_NAME_MAX: u32 = 255;
pub const BTRFS_PATH_NAME_MAX: u32 = 4087;
pub const BTRFS_DEVICE_PATH_NAME_MAX: u32 = 1024;
pub const BTRFS_SUBVOL_RDONLY: u32 = 2;
pub const BTRFS_SUBVOL_QGROUP_INHERIT: u32 = 4;
pub const BTRFS_DEVICE_SPEC_BY_ID: u32 = 8;
pub const BTRFS_SUBVOL_SPEC_BY_ID: u32 = 16;
pub const BTRFS_VOL_ARG_V2_FLAGS_SUPPORTED: u32 = 30;
pub const BTRFS_FSID_SIZE: u32 = 16;
pub const BTRFS_UUID_SIZE: u32 = 16;
pub const BTRFS_QGROUP_INHERIT_SET_LIMITS: u32 = 1;
pub const BTRFS_SUBVOL_NAME_MAX: u32 = 4039;
pub const BTRFS_SCRUB_READONLY: u32 = 1;
pub const BTRFS_IOCTL_DEV_REPLACE_CONT_READING_FROM_SRCDEV_MODE_ALWAYS: u32 = 0;
pub const BTRFS_IOCTL_DEV_REPLACE_CONT_READING_FROM_SRCDEV_MODE_AVOID: u32 = 1;
pub const BTRFS_IOCTL_DEV_REPLACE_STATE_NEVER_STARTED: u32 = 0;
pub const BTRFS_IOCTL_DEV_REPLACE_STATE_STARTED: u32 = 1;
pub const BTRFS_IOCTL_DEV_REPLACE_STATE_FINISHED: u32 = 2;
pub const BTRFS_IOCTL_DEV_REPLACE_STATE_CANCELED: u32 = 3;
pub const BTRFS_IOCTL_DEV_REPLACE_STATE_SUSPENDED: u32 = 4;
pub const BTRFS_IOCTL_DEV_REPLACE_CMD_START: u32 = 0;
pub const BTRFS_IOCTL_DEV_REPLACE_CMD_STATUS: u32 = 1;
pub const BTRFS_IOCTL_DEV_REPLACE_CMD_CANCEL: u32 = 2;
pub const BTRFS_IOCTL_DEV_REPLACE_RESULT_NO_RESULT: i32 = -1;
pub const BTRFS_IOCTL_DEV_REPLACE_RESULT_NO_ERROR: u32 = 0;
pub const BTRFS_IOCTL_DEV_REPLACE_RESULT_NOT_STARTED: u32 = 1;
pub const BTRFS_IOCTL_DEV_REPLACE_RESULT_ALREADY_STARTED: u32 = 2;
pub const BTRFS_IOCTL_DEV_REPLACE_RESULT_SCRUB_INPROGRESS: u32 = 3;
pub const BTRFS_BALANCE_CTL_PAUSE: u32 = 1;
pub const BTRFS_BALANCE_CTL_CANCEL: u32 = 2;
pub const BTRFS_BALANCE_CTL_RESUME: u32 = 3;
pub const BTRFS_BALANCE_STATE_RUNNING: u32 = 1;
pub const BTRFS_BALANCE_STATE_PAUSE_REQ: u32 = 2;
pub const BTRFS_BALANCE_STATE_CANCEL_REQ: u32 = 4;
pub const BTRFS_INO_LOOKUP_PATH_MAX: u32 = 4080;
pub const BTRFS_INO_LOOKUP_USER_PATH_MAX: u32 = 3824;
pub const BTRFS_DEFRAG_RANGE_COMPRESS: u32 = 1;
pub const BTRFS_DEFRAG_RANGE_START_IO: u32 = 2;
pub const BTRFS_SAME_DATA_DIFFERS: u32 = 1;
pub const BTRFS_LOGICAL_INO_ARGS_IGNORE_OFFSET: u32 = 1;
pub const BTRFS_DEV_STATS_RESET: u32 = 1;
pub const BTRFS_QUOTA_CTL_ENABLE: u32 = 1;
pub const BTRFS_QUOTA_CTL_DISABLE: u32 = 2;
pub const BTRFS_IOC_SET_RECEIVED_SUBVOL_32_COMPAT_DEFINED: u32 = 1;
pub const BTRFS_SEND_FLAG_NO_FILE_DATA: u32 = 1;
pub const BTRFS_SEND_FLAG_OMIT_STREAM_HEADER: u32 = 2;
pub const BTRFS_SEND_FLAG_OMIT_END_CMD: u32 = 4;
pub const BTRFS_SEND_FLAG_VERSION: u32 = 8;
pub const BTRFS_SEND_FLAG_COMPRESSED: u32 = 16;
pub const BTRFS_SEND_FLAG_MASK: u32 = 31;
pub const BTRFS_IOC_SEND_64_COMPAT_DEFINED: u32 = 1;
pub const BTRFS_MAX_ROOTREF_BUFFER_NUM: u32 = 255;
pub const BTRFS_ENCODED_IO_COMPRESSION_NONE: u32 = 0;
pub const BTRFS_ENCODED_IO_COMPRESSION_ZLIB: u32 = 1;
pub const BTRFS_ENCODED_IO_COMPRESSION_ZSTD: u32 = 2;
pub const BTRFS_ENCODED_IO_COMPRESSION_LZO_4K: u32 = 3;
pub const BTRFS_ENCODED_IO_COMPRESSION_LZO_8K: u32 = 4;
pub const BTRFS_ENCODED_IO_COMPRESSION_LZO_16K: u32 = 5;
pub const BTRFS_ENCODED_IO_COMPRESSION_LZO_32K: u32 = 6;
pub const BTRFS_ENCODED_IO_COMPRESSION_LZO_64K: u32 = 7;
pub const BTRFS_ENCODED_IO_COMPRESSION_TYPES: u32 = 8;
pub const BTRFS_ENCODED_IO_ENCRYPTION_NONE: u32 = 0;
pub const BTRFS_ENCODED_IO_ENCRYPTION_TYPES: u32 = 1;
pub type __s8 = ::std::os::raw::c_schar;
pub type __u8 = ::std::os::raw::c_uchar;
pub type __s16 = ::std::os::raw::c_short;
pub type __u16 = ::std::os::raw::c_ushort;
pub type __s32 = ::std::os::raw::c_int;
pub type __u32 = ::std::os::raw::c_uint;
pub type __s64 = ::std::os::raw::c_longlong;
pub type __u64 = ::std::os::raw::c_ulonglong;
pub type wchar_t = ::std::os::raw::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of max_align_t"][::std::mem::size_of::<max_align_t>() - 32usize];
    ["Alignment of max_align_t"][::std::mem::align_of::<max_align_t>() - 16usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce1"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce1) - 0usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce2"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce2) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_vol_args {
    pub fd: __s64,
    pub name: [::std::os::raw::c_char; 4088usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_vol_args"][::std::mem::size_of::<btrfs_ioctl_vol_args>() - 4096usize];
    ["Alignment of btrfs_ioctl_vol_args"][::std::mem::align_of::<btrfs_ioctl_vol_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_vol_args::fd"]
        [::std::mem::offset_of!(btrfs_ioctl_vol_args, fd) - 0usize];
    ["Offset of field: btrfs_ioctl_vol_args::name"]
        [::std::mem::offset_of!(btrfs_ioctl_vol_args, name) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_qgroup_limit {
    pub flags: __u64,
    pub max_referenced: __u64,
    pub max_exclusive: __u64,
    pub rsv_referenced: __u64,
    pub rsv_exclusive: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_qgroup_limit"][::std::mem::size_of::<btrfs_qgroup_limit>() - 40usize];
    ["Alignment of btrfs_qgroup_limit"][::std::mem::align_of::<btrfs_qgroup_limit>() - 8usize];
    ["Offset of field: btrfs_qgroup_limit::flags"]
        [::std::mem::offset_of!(btrfs_qgroup_limit, flags) - 0usize];
    ["Offset of field: btrfs_qgroup_limit::max_referenced"]
        [::std::mem::offset_of!(btrfs_qgroup_limit, max_referenced) - 8usize];
    ["Offset of field: btrfs_qgroup_limit::max_exclusive"]
        [::std::mem::offset_of!(btrfs_qgroup_limit, max_exclusive) - 16usize];
    ["Offset of field: btrfs_qgroup_limit::rsv_referenced"]
        [::std::mem::offset_of!(btrfs_qgroup_limit, rsv_referenced) - 24usize];
    ["Offset of field: btrfs_qgroup_limit::rsv_exclusive"]
        [::std::mem::offset_of!(btrfs_qgroup_limit, rsv_exclusive) - 32usize];
};
#[repr(C)]
#[derive(Debug)]
pub struct btrfs_qgroup_inherit {
    pub flags: __u64,
    pub num_qgroups: __u64,
    pub num_ref_copies: __u64,
    pub num_excl_copies: __u64,
    pub lim: btrfs_qgroup_limit,
    pub qgroups: __IncompleteArrayField<__u64>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_qgroup_inherit"][::std::mem::size_of::<btrfs_qgroup_inherit>() - 72usize];
    ["Alignment of btrfs_qgroup_inherit"][::std::mem::align_of::<btrfs_qgroup_inherit>() - 8usize];
    ["Offset of field: btrfs_qgroup_inherit::flags"]
        [::std::mem::offset_of!(btrfs_qgroup_inherit, flags) - 0usize];
    ["Offset of field: btrfs_qgroup_inherit::num_qgroups"]
        [::std::mem::offset_of!(btrfs_qgroup_inherit, num_qgroups) - 8usize];
    ["Offset of field: btrfs_qgroup_inherit::num_ref_copies"]
        [::std::mem::offset_of!(btrfs_qgroup_inherit, num_ref_copies) - 16usize];
    ["Offset of field: btrfs_qgroup_inherit::num_excl_copies"]
        [::std::mem::offset_of!(btrfs_qgroup_inherit, num_excl_copies) - 24usize];
    ["Offset of field: btrfs_qgroup_inherit::lim"]
        [::std::mem::offset_of!(btrfs_qgroup_inherit, lim) - 32usize];
    ["Offset of field: btrfs_qgroup_inherit::qgroups"]
        [::std::mem::offset_of!(btrfs_qgroup_inherit, qgroups) - 72usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_qgroup_limit_args {
    pub qgroupid: __u64,
    pub lim: btrfs_qgroup_limit,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_qgroup_limit_args"]
        [::std::mem::size_of::<btrfs_ioctl_qgroup_limit_args>() - 48usize];
    ["Alignment of btrfs_ioctl_qgroup_limit_args"]
        [::std::mem::align_of::<btrfs_ioctl_qgroup_limit_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_qgroup_limit_args::qgroupid"]
        [::std::mem::offset_of!(btrfs_ioctl_qgroup_limit_args, qgroupid) - 0usize];
    ["Offset of field: btrfs_ioctl_qgroup_limit_args::lim"]
        [::std::mem::offset_of!(btrfs_ioctl_qgroup_limit_args, lim) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct btrfs_ioctl_vol_args_v2 {
    pub fd: __s64,
    pub transid: __u64,
    pub flags: __u64,
    pub __bindgen_anon_1: btrfs_ioctl_vol_args_v2__bindgen_ty_1,
    pub __bindgen_anon_2: btrfs_ioctl_vol_args_v2__bindgen_ty_2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union btrfs_ioctl_vol_args_v2__bindgen_ty_1 {
    pub __bindgen_anon_1: btrfs_ioctl_vol_args_v2__bindgen_ty_1__bindgen_ty_1,
    pub unused: [__u64; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_vol_args_v2__bindgen_ty_1__bindgen_ty_1 {
    pub size: __u64,
    pub qgroup_inherit: *mut btrfs_qgroup_inherit,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_vol_args_v2__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<btrfs_ioctl_vol_args_v2__bindgen_ty_1__bindgen_ty_1>() - 16usize];
    ["Alignment of btrfs_ioctl_vol_args_v2__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<btrfs_ioctl_vol_args_v2__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: btrfs_ioctl_vol_args_v2__bindgen_ty_1__bindgen_ty_1::size"][::std::mem::offset_of!(
        btrfs_ioctl_vol_args_v2__bindgen_ty_1__bindgen_ty_1,
        size
    ) - 0usize];
    ["Offset of field: btrfs_ioctl_vol_args_v2__bindgen_ty_1__bindgen_ty_1::qgroup_inherit"][::std::mem::offset_of!(
        btrfs_ioctl_vol_args_v2__bindgen_ty_1__bindgen_ty_1,
        qgroup_inherit
    )
        - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_vol_args_v2__bindgen_ty_1"]
        [::std::mem::size_of::<btrfs_ioctl_vol_args_v2__bindgen_ty_1>() - 32usize];
    ["Alignment of btrfs_ioctl_vol_args_v2__bindgen_ty_1"]
        [::std::mem::align_of::<btrfs_ioctl_vol_args_v2__bindgen_ty_1>() - 8usize];
    ["Offset of field: btrfs_ioctl_vol_args_v2__bindgen_ty_1::unused"]
        [::std::mem::offset_of!(btrfs_ioctl_vol_args_v2__bindgen_ty_1, unused) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union btrfs_ioctl_vol_args_v2__bindgen_ty_2 {
    pub name: [::std::os::raw::c_char; 4040usize],
    pub devid: __u64,
    pub subvolid: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_vol_args_v2__bindgen_ty_2"]
        [::std::mem::size_of::<btrfs_ioctl_vol_args_v2__bindgen_ty_2>() - 4040usize];
    ["Alignment of btrfs_ioctl_vol_args_v2__bindgen_ty_2"]
        [::std::mem::align_of::<btrfs_ioctl_vol_args_v2__bindgen_ty_2>() - 8usize];
    ["Offset of field: btrfs_ioctl_vol_args_v2__bindgen_ty_2::name"]
        [::std::mem::offset_of!(btrfs_ioctl_vol_args_v2__bindgen_ty_2, name) - 0usize];
    ["Offset of field: btrfs_ioctl_vol_args_v2__bindgen_ty_2::devid"]
        [::std::mem::offset_of!(btrfs_ioctl_vol_args_v2__bindgen_ty_2, devid) - 0usize];
    ["Offset of field: btrfs_ioctl_vol_args_v2__bindgen_ty_2::subvolid"]
        [::std::mem::offset_of!(btrfs_ioctl_vol_args_v2__bindgen_ty_2, subvolid) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_vol_args_v2"]
        [::std::mem::size_of::<btrfs_ioctl_vol_args_v2>() - 4096usize];
    ["Alignment of btrfs_ioctl_vol_args_v2"]
        [::std::mem::align_of::<btrfs_ioctl_vol_args_v2>() - 8usize];
    ["Offset of field: btrfs_ioctl_vol_args_v2::fd"]
        [::std::mem::offset_of!(btrfs_ioctl_vol_args_v2, fd) - 0usize];
    ["Offset of field: btrfs_ioctl_vol_args_v2::transid"]
        [::std::mem::offset_of!(btrfs_ioctl_vol_args_v2, transid) - 8usize];
    ["Offset of field: btrfs_ioctl_vol_args_v2::flags"]
        [::std::mem::offset_of!(btrfs_ioctl_vol_args_v2, flags) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_scrub_progress {
    pub data_extents_scrubbed: __u64,
    pub tree_extents_scrubbed: __u64,
    pub data_bytes_scrubbed: __u64,
    pub tree_bytes_scrubbed: __u64,
    pub read_errors: __u64,
    pub csum_errors: __u64,
    pub verify_errors: __u64,
    pub no_csum: __u64,
    pub csum_discards: __u64,
    pub super_errors: __u64,
    pub malloc_errors: __u64,
    pub uncorrectable_errors: __u64,
    pub corrected_errors: __u64,
    pub last_physical: __u64,
    pub unverified_errors: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_scrub_progress"][::std::mem::size_of::<btrfs_scrub_progress>() - 120usize];
    ["Alignment of btrfs_scrub_progress"][::std::mem::align_of::<btrfs_scrub_progress>() - 8usize];
    ["Offset of field: btrfs_scrub_progress::data_extents_scrubbed"]
        [::std::mem::offset_of!(btrfs_scrub_progress, data_extents_scrubbed) - 0usize];
    ["Offset of field: btrfs_scrub_progress::tree_extents_scrubbed"]
        [::std::mem::offset_of!(btrfs_scrub_progress, tree_extents_scrubbed) - 8usize];
    ["Offset of field: btrfs_scrub_progress::data_bytes_scrubbed"]
        [::std::mem::offset_of!(btrfs_scrub_progress, data_bytes_scrubbed) - 16usize];
    ["Offset of field: btrfs_scrub_progress::tree_bytes_scrubbed"]
        [::std::mem::offset_of!(btrfs_scrub_progress, tree_bytes_scrubbed) - 24usize];
    ["Offset of field: btrfs_scrub_progress::read_errors"]
        [::std::mem::offset_of!(btrfs_scrub_progress, read_errors) - 32usize];
    ["Offset of field: btrfs_scrub_progress::csum_errors"]
        [::std::mem::offset_of!(btrfs_scrub_progress, csum_errors) - 40usize];
    ["Offset of field: btrfs_scrub_progress::verify_errors"]
        [::std::mem::offset_of!(btrfs_scrub_progress, verify_errors) - 48usize];
    ["Offset of field: btrfs_scrub_progress::no_csum"]
        [::std::mem::offset_of!(btrfs_scrub_progress, no_csum) - 56usize];
    ["Offset of field: btrfs_scrub_progress::csum_discards"]
        [::std::mem::offset_of!(btrfs_scrub_progress, csum_discards) - 64usize];
    ["Offset of field: btrfs_scrub_progress::super_errors"]
        [::std::mem::offset_of!(btrfs_scrub_progress, super_errors) - 72usize];
    ["Offset of field: btrfs_scrub_progress::malloc_errors"]
        [::std::mem::offset_of!(btrfs_scrub_progress, malloc_errors) - 80usize];
    ["Offset of field: btrfs_scrub_progress::uncorrectable_errors"]
        [::std::mem::offset_of!(btrfs_scrub_progress, uncorrectable_errors) - 88usize];
    ["Offset of field: btrfs_scrub_progress::corrected_errors"]
        [::std::mem::offset_of!(btrfs_scrub_progress, corrected_errors) - 96usize];
    ["Offset of field: btrfs_scrub_progress::last_physical"]
        [::std::mem::offset_of!(btrfs_scrub_progress, last_physical) - 104usize];
    ["Offset of field: btrfs_scrub_progress::unverified_errors"]
        [::std::mem::offset_of!(btrfs_scrub_progress, unverified_errors) - 112usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_scrub_args {
    pub devid: __u64,
    pub start: __u64,
    pub end: __u64,
    pub flags: __u64,
    pub progress: btrfs_scrub_progress,
    pub unused: [__u64; 109usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_scrub_args"][::std::mem::size_of::<btrfs_ioctl_scrub_args>() - 1024usize];
    ["Alignment of btrfs_ioctl_scrub_args"]
        [::std::mem::align_of::<btrfs_ioctl_scrub_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_scrub_args::devid"]
        [::std::mem::offset_of!(btrfs_ioctl_scrub_args, devid) - 0usize];
    ["Offset of field: btrfs_ioctl_scrub_args::start"]
        [::std::mem::offset_of!(btrfs_ioctl_scrub_args, start) - 8usize];
    ["Offset of field: btrfs_ioctl_scrub_args::end"]
        [::std::mem::offset_of!(btrfs_ioctl_scrub_args, end) - 16usize];
    ["Offset of field: btrfs_ioctl_scrub_args::flags"]
        [::std::mem::offset_of!(btrfs_ioctl_scrub_args, flags) - 24usize];
    ["Offset of field: btrfs_ioctl_scrub_args::progress"]
        [::std::mem::offset_of!(btrfs_ioctl_scrub_args, progress) - 32usize];
    ["Offset of field: btrfs_ioctl_scrub_args::unused"]
        [::std::mem::offset_of!(btrfs_ioctl_scrub_args, unused) - 152usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_dev_replace_start_params {
    pub srcdevid: __u64,
    pub cont_reading_from_srcdev_mode: __u64,
    pub srcdev_name: [__u8; 1025usize],
    pub tgtdev_name: [__u8; 1025usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_dev_replace_start_params"]
        [::std::mem::size_of::<btrfs_ioctl_dev_replace_start_params>() - 2072usize];
    ["Alignment of btrfs_ioctl_dev_replace_start_params"]
        [::std::mem::align_of::<btrfs_ioctl_dev_replace_start_params>() - 8usize];
    ["Offset of field: btrfs_ioctl_dev_replace_start_params::srcdevid"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_replace_start_params, srcdevid) - 0usize];
    ["Offset of field: btrfs_ioctl_dev_replace_start_params::cont_reading_from_srcdev_mode"][::std::mem::offset_of!(
        btrfs_ioctl_dev_replace_start_params,
        cont_reading_from_srcdev_mode
    )
        - 8usize];
    ["Offset of field: btrfs_ioctl_dev_replace_start_params::srcdev_name"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_replace_start_params, srcdev_name) - 16usize];
    ["Offset of field: btrfs_ioctl_dev_replace_start_params::tgtdev_name"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_replace_start_params, tgtdev_name) - 1041usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_dev_replace_status_params {
    pub replace_state: __u64,
    pub progress_1000: __u64,
    pub time_started: __u64,
    pub time_stopped: __u64,
    pub num_write_errors: __u64,
    pub num_uncorrectable_read_errors: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_dev_replace_status_params"]
        [::std::mem::size_of::<btrfs_ioctl_dev_replace_status_params>() - 48usize];
    ["Alignment of btrfs_ioctl_dev_replace_status_params"]
        [::std::mem::align_of::<btrfs_ioctl_dev_replace_status_params>() - 8usize];
    ["Offset of field: btrfs_ioctl_dev_replace_status_params::replace_state"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_replace_status_params, replace_state) - 0usize];
    ["Offset of field: btrfs_ioctl_dev_replace_status_params::progress_1000"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_replace_status_params, progress_1000) - 8usize];
    ["Offset of field: btrfs_ioctl_dev_replace_status_params::time_started"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_replace_status_params, time_started) - 16usize];
    ["Offset of field: btrfs_ioctl_dev_replace_status_params::time_stopped"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_replace_status_params, time_stopped) - 24usize];
    ["Offset of field: btrfs_ioctl_dev_replace_status_params::num_write_errors"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_replace_status_params, num_write_errors) - 32usize];
    ["Offset of field: btrfs_ioctl_dev_replace_status_params::num_uncorrectable_read_errors"][::std::mem::offset_of!(
        btrfs_ioctl_dev_replace_status_params,
        num_uncorrectable_read_errors
    )
        - 40usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct btrfs_ioctl_dev_replace_args {
    pub cmd: __u64,
    pub result: __u64,
    pub __bindgen_anon_1: btrfs_ioctl_dev_replace_args__bindgen_ty_1,
    pub spare: [__u64; 64usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union btrfs_ioctl_dev_replace_args__bindgen_ty_1 {
    pub start: btrfs_ioctl_dev_replace_start_params,
    pub status: btrfs_ioctl_dev_replace_status_params,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_dev_replace_args__bindgen_ty_1"]
        [::std::mem::size_of::<btrfs_ioctl_dev_replace_args__bindgen_ty_1>() - 2072usize];
    ["Alignment of btrfs_ioctl_dev_replace_args__bindgen_ty_1"]
        [::std::mem::align_of::<btrfs_ioctl_dev_replace_args__bindgen_ty_1>() - 8usize];
    ["Offset of field: btrfs_ioctl_dev_replace_args__bindgen_ty_1::start"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_replace_args__bindgen_ty_1, start) - 0usize];
    ["Offset of field: btrfs_ioctl_dev_replace_args__bindgen_ty_1::status"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_replace_args__bindgen_ty_1, status) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_dev_replace_args"]
        [::std::mem::size_of::<btrfs_ioctl_dev_replace_args>() - 2600usize];
    ["Alignment of btrfs_ioctl_dev_replace_args"]
        [::std::mem::align_of::<btrfs_ioctl_dev_replace_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_dev_replace_args::cmd"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_replace_args, cmd) - 0usize];
    ["Offset of field: btrfs_ioctl_dev_replace_args::result"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_replace_args, result) - 8usize];
    ["Offset of field: btrfs_ioctl_dev_replace_args::spare"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_replace_args, spare) - 2088usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_dev_info_args {
    pub devid: __u64,
    pub uuid: [__u8; 16usize],
    pub bytes_used: __u64,
    pub total_bytes: __u64,
    pub unused: [__u64; 379usize],
    pub path: [__u8; 1024usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_dev_info_args"]
        [::std::mem::size_of::<btrfs_ioctl_dev_info_args>() - 4096usize];
    ["Alignment of btrfs_ioctl_dev_info_args"]
        [::std::mem::align_of::<btrfs_ioctl_dev_info_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_dev_info_args::devid"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_info_args, devid) - 0usize];
    ["Offset of field: btrfs_ioctl_dev_info_args::uuid"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_info_args, uuid) - 8usize];
    ["Offset of field: btrfs_ioctl_dev_info_args::bytes_used"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_info_args, bytes_used) - 24usize];
    ["Offset of field: btrfs_ioctl_dev_info_args::total_bytes"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_info_args, total_bytes) - 32usize];
    ["Offset of field: btrfs_ioctl_dev_info_args::unused"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_info_args, unused) - 40usize];
    ["Offset of field: btrfs_ioctl_dev_info_args::path"]
        [::std::mem::offset_of!(btrfs_ioctl_dev_info_args, path) - 3072usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_fs_info_args {
    pub max_id: __u64,
    pub num_devices: __u64,
    pub fsid: [__u8; 16usize],
    pub nodesize: __u32,
    pub sectorsize: __u32,
    pub clone_alignment: __u32,
    pub reserved32: __u32,
    pub reserved: [__u64; 122usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_fs_info_args"]
        [::std::mem::size_of::<btrfs_ioctl_fs_info_args>() - 1024usize];
    ["Alignment of btrfs_ioctl_fs_info_args"]
        [::std::mem::align_of::<btrfs_ioctl_fs_info_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_fs_info_args::max_id"]
        [::std::mem::offset_of!(btrfs_ioctl_fs_info_args, max_id) - 0usize];
    ["Offset of field: btrfs_ioctl_fs_info_args::num_devices"]
        [::std::mem::offset_of!(btrfs_ioctl_fs_info_args, num_devices) - 8usize];
    ["Offset of field: btrfs_ioctl_fs_info_args::fsid"]
        [::std::mem::offset_of!(btrfs_ioctl_fs_info_args, fsid) - 16usize];
    ["Offset of field: btrfs_ioctl_fs_info_args::nodesize"]
        [::std::mem::offset_of!(btrfs_ioctl_fs_info_args, nodesize) - 32usize];
    ["Offset of field: btrfs_ioctl_fs_info_args::sectorsize"]
        [::std::mem::offset_of!(btrfs_ioctl_fs_info_args, sectorsize) - 36usize];
    ["Offset of field: btrfs_ioctl_fs_info_args::clone_alignment"]
        [::std::mem::offset_of!(btrfs_ioctl_fs_info_args, clone_alignment) - 40usize];
    ["Offset of field: btrfs_ioctl_fs_info_args::reserved32"]
        [::std::mem::offset_of!(btrfs_ioctl_fs_info_args, reserved32) - 44usize];
    ["Offset of field: btrfs_ioctl_fs_info_args::reserved"]
        [::std::mem::offset_of!(btrfs_ioctl_fs_info_args, reserved) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_feature_flags {
    pub compat_flags: __u64,
    pub compat_ro_flags: __u64,
    pub incompat_flags: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_feature_flags"]
        [::std::mem::size_of::<btrfs_ioctl_feature_flags>() - 24usize];
    ["Alignment of btrfs_ioctl_feature_flags"]
        [::std::mem::align_of::<btrfs_ioctl_feature_flags>() - 8usize];
    ["Offset of field: btrfs_ioctl_feature_flags::compat_flags"]
        [::std::mem::offset_of!(btrfs_ioctl_feature_flags, compat_flags) - 0usize];
    ["Offset of field: btrfs_ioctl_feature_flags::compat_ro_flags"]
        [::std::mem::offset_of!(btrfs_ioctl_feature_flags, compat_ro_flags) - 8usize];
    ["Offset of field: btrfs_ioctl_feature_flags::incompat_flags"]
        [::std::mem::offset_of!(btrfs_ioctl_feature_flags, incompat_flags) - 16usize];
};
#[repr(C, packed)]
#[derive(Copy, Clone)]
pub struct btrfs_balance_args {
    pub profiles: __u64,
    pub __bindgen_anon_1: btrfs_balance_args__bindgen_ty_1,
    pub devid: __u64,
    pub pstart: __u64,
    pub pend: __u64,
    pub vstart: __u64,
    pub vend: __u64,
    pub target: __u64,
    pub flags: __u64,
    pub __bindgen_anon_2: btrfs_balance_args__bindgen_ty_2,
    pub stripes_min: __u32,
    pub stripes_max: __u32,
    pub unused: [__u64; 6usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union btrfs_balance_args__bindgen_ty_1 {
    pub usage: __u64,
    pub __bindgen_anon_1: btrfs_balance_args__bindgen_ty_1__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_balance_args__bindgen_ty_1__bindgen_ty_1 {
    pub usage_min: __u32,
    pub usage_max: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_balance_args__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<btrfs_balance_args__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Alignment of btrfs_balance_args__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<btrfs_balance_args__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Offset of field: btrfs_balance_args__bindgen_ty_1__bindgen_ty_1::usage_min"][::std::mem::offset_of!(
        btrfs_balance_args__bindgen_ty_1__bindgen_ty_1,
        usage_min
    ) - 0usize];
    ["Offset of field: btrfs_balance_args__bindgen_ty_1__bindgen_ty_1::usage_max"][::std::mem::offset_of!(
        btrfs_balance_args__bindgen_ty_1__bindgen_ty_1,
        usage_max
    ) - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_balance_args__bindgen_ty_1"]
        [::std::mem::size_of::<btrfs_balance_args__bindgen_ty_1>() - 8usize];
    ["Alignment of btrfs_balance_args__bindgen_ty_1"]
        [::std::mem::align_of::<btrfs_balance_args__bindgen_ty_1>() - 8usize];
    ["Offset of field: btrfs_balance_args__bindgen_ty_1::usage"]
        [::std::mem::offset_of!(btrfs_balance_args__bindgen_ty_1, usage) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union btrfs_balance_args__bindgen_ty_2 {
    pub limit: __u64,
    pub __bindgen_anon_1: btrfs_balance_args__bindgen_ty_2__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_balance_args__bindgen_ty_2__bindgen_ty_1 {
    pub limit_min: __u32,
    pub limit_max: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_balance_args__bindgen_ty_2__bindgen_ty_1"]
        [::std::mem::size_of::<btrfs_balance_args__bindgen_ty_2__bindgen_ty_1>() - 8usize];
    ["Alignment of btrfs_balance_args__bindgen_ty_2__bindgen_ty_1"]
        [::std::mem::align_of::<btrfs_balance_args__bindgen_ty_2__bindgen_ty_1>() - 4usize];
    ["Offset of field: btrfs_balance_args__bindgen_ty_2__bindgen_ty_1::limit_min"][::std::mem::offset_of!(
        btrfs_balance_args__bindgen_ty_2__bindgen_ty_1,
        limit_min
    ) - 0usize];
    ["Offset of field: btrfs_balance_args__bindgen_ty_2__bindgen_ty_1::limit_max"][::std::mem::offset_of!(
        btrfs_balance_args__bindgen_ty_2__bindgen_ty_1,
        limit_max
    ) - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_balance_args__bindgen_ty_2"]
        [::std::mem::size_of::<btrfs_balance_args__bindgen_ty_2>() - 8usize];
    ["Alignment of btrfs_balance_args__bindgen_ty_2"]
        [::std::mem::align_of::<btrfs_balance_args__bindgen_ty_2>() - 8usize];
    ["Offset of field: btrfs_balance_args__bindgen_ty_2::limit"]
        [::std::mem::offset_of!(btrfs_balance_args__bindgen_ty_2, limit) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_balance_args"][::std::mem::size_of::<btrfs_balance_args>() - 136usize];
    ["Alignment of btrfs_balance_args"][::std::mem::align_of::<btrfs_balance_args>() - 1usize];
    ["Offset of field: btrfs_balance_args::profiles"]
        [::std::mem::offset_of!(btrfs_balance_args, profiles) - 0usize];
    ["Offset of field: btrfs_balance_args::devid"]
        [::std::mem::offset_of!(btrfs_balance_args, devid) - 16usize];
    ["Offset of field: btrfs_balance_args::pstart"]
        [::std::mem::offset_of!(btrfs_balance_args, pstart) - 24usize];
    ["Offset of field: btrfs_balance_args::pend"]
        [::std::mem::offset_of!(btrfs_balance_args, pend) - 32usize];
    ["Offset of field: btrfs_balance_args::vstart"]
        [::std::mem::offset_of!(btrfs_balance_args, vstart) - 40usize];
    ["Offset of field: btrfs_balance_args::vend"]
        [::std::mem::offset_of!(btrfs_balance_args, vend) - 48usize];
    ["Offset of field: btrfs_balance_args::target"]
        [::std::mem::offset_of!(btrfs_balance_args, target) - 56usize];
    ["Offset of field: btrfs_balance_args::flags"]
        [::std::mem::offset_of!(btrfs_balance_args, flags) - 64usize];
    ["Offset of field: btrfs_balance_args::stripes_min"]
        [::std::mem::offset_of!(btrfs_balance_args, stripes_min) - 80usize];
    ["Offset of field: btrfs_balance_args::stripes_max"]
        [::std::mem::offset_of!(btrfs_balance_args, stripes_max) - 84usize];
    ["Offset of field: btrfs_balance_args::unused"]
        [::std::mem::offset_of!(btrfs_balance_args, unused) - 88usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_balance_progress {
    pub expected: __u64,
    pub considered: __u64,
    pub completed: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_balance_progress"][::std::mem::size_of::<btrfs_balance_progress>() - 24usize];
    ["Alignment of btrfs_balance_progress"]
        [::std::mem::align_of::<btrfs_balance_progress>() - 8usize];
    ["Offset of field: btrfs_balance_progress::expected"]
        [::std::mem::offset_of!(btrfs_balance_progress, expected) - 0usize];
    ["Offset of field: btrfs_balance_progress::considered"]
        [::std::mem::offset_of!(btrfs_balance_progress, considered) - 8usize];
    ["Offset of field: btrfs_balance_progress::completed"]
        [::std::mem::offset_of!(btrfs_balance_progress, completed) - 16usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct btrfs_ioctl_balance_args {
    pub flags: __u64,
    pub state: __u64,
    pub data: btrfs_balance_args,
    pub meta: btrfs_balance_args,
    pub sys: btrfs_balance_args,
    pub stat: btrfs_balance_progress,
    pub unused: [__u64; 72usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_balance_args"]
        [::std::mem::size_of::<btrfs_ioctl_balance_args>() - 1024usize];
    ["Alignment of btrfs_ioctl_balance_args"]
        [::std::mem::align_of::<btrfs_ioctl_balance_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_balance_args::flags"]
        [::std::mem::offset_of!(btrfs_ioctl_balance_args, flags) - 0usize];
    ["Offset of field: btrfs_ioctl_balance_args::state"]
        [::std::mem::offset_of!(btrfs_ioctl_balance_args, state) - 8usize];
    ["Offset of field: btrfs_ioctl_balance_args::data"]
        [::std::mem::offset_of!(btrfs_ioctl_balance_args, data) - 16usize];
    ["Offset of field: btrfs_ioctl_balance_args::meta"]
        [::std::mem::offset_of!(btrfs_ioctl_balance_args, meta) - 152usize];
    ["Offset of field: btrfs_ioctl_balance_args::sys"]
        [::std::mem::offset_of!(btrfs_ioctl_balance_args, sys) - 288usize];
    ["Offset of field: btrfs_ioctl_balance_args::stat"]
        [::std::mem::offset_of!(btrfs_ioctl_balance_args, stat) - 424usize];
    ["Offset of field: btrfs_ioctl_balance_args::unused"]
        [::std::mem::offset_of!(btrfs_ioctl_balance_args, unused) - 448usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_ino_lookup_args {
    pub treeid: __u64,
    pub objectid: __u64,
    pub name: [::std::os::raw::c_char; 4080usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_ino_lookup_args"]
        [::std::mem::size_of::<btrfs_ioctl_ino_lookup_args>() - 4096usize];
    ["Alignment of btrfs_ioctl_ino_lookup_args"]
        [::std::mem::align_of::<btrfs_ioctl_ino_lookup_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_ino_lookup_args::treeid"]
        [::std::mem::offset_of!(btrfs_ioctl_ino_lookup_args, treeid) - 0usize];
    ["Offset of field: btrfs_ioctl_ino_lookup_args::objectid"]
        [::std::mem::offset_of!(btrfs_ioctl_ino_lookup_args, objectid) - 8usize];
    ["Offset of field: btrfs_ioctl_ino_lookup_args::name"]
        [::std::mem::offset_of!(btrfs_ioctl_ino_lookup_args, name) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_ino_lookup_user_args {
    pub dirid: __u64,
    pub treeid: __u64,
    pub name: [::std::os::raw::c_char; 256usize],
    pub path: [::std::os::raw::c_char; 3824usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_ino_lookup_user_args"]
        [::std::mem::size_of::<btrfs_ioctl_ino_lookup_user_args>() - 4096usize];
    ["Alignment of btrfs_ioctl_ino_lookup_user_args"]
        [::std::mem::align_of::<btrfs_ioctl_ino_lookup_user_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_ino_lookup_user_args::dirid"]
        [::std::mem::offset_of!(btrfs_ioctl_ino_lookup_user_args, dirid) - 0usize];
    ["Offset of field: btrfs_ioctl_ino_lookup_user_args::treeid"]
        [::std::mem::offset_of!(btrfs_ioctl_ino_lookup_user_args, treeid) - 8usize];
    ["Offset of field: btrfs_ioctl_ino_lookup_user_args::name"]
        [::std::mem::offset_of!(btrfs_ioctl_ino_lookup_user_args, name) - 16usize];
    ["Offset of field: btrfs_ioctl_ino_lookup_user_args::path"]
        [::std::mem::offset_of!(btrfs_ioctl_ino_lookup_user_args, path) - 272usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_search_key {
    pub tree_id: __u64,
    pub min_objectid: __u64,
    pub max_objectid: __u64,
    pub min_offset: __u64,
    pub max_offset: __u64,
    pub min_transid: __u64,
    pub max_transid: __u64,
    pub min_type: __u32,
    pub max_type: __u32,
    pub nr_items: __u32,
    pub unused: __u32,
    pub unused1: __u64,
    pub unused2: __u64,
    pub unused3: __u64,
    pub unused4: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_search_key"][::std::mem::size_of::<btrfs_ioctl_search_key>() - 104usize];
    ["Alignment of btrfs_ioctl_search_key"]
        [::std::mem::align_of::<btrfs_ioctl_search_key>() - 8usize];
    ["Offset of field: btrfs_ioctl_search_key::tree_id"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, tree_id) - 0usize];
    ["Offset of field: btrfs_ioctl_search_key::min_objectid"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, min_objectid) - 8usize];
    ["Offset of field: btrfs_ioctl_search_key::max_objectid"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, max_objectid) - 16usize];
    ["Offset of field: btrfs_ioctl_search_key::min_offset"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, min_offset) - 24usize];
    ["Offset of field: btrfs_ioctl_search_key::max_offset"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, max_offset) - 32usize];
    ["Offset of field: btrfs_ioctl_search_key::min_transid"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, min_transid) - 40usize];
    ["Offset of field: btrfs_ioctl_search_key::max_transid"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, max_transid) - 48usize];
    ["Offset of field: btrfs_ioctl_search_key::min_type"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, min_type) - 56usize];
    ["Offset of field: btrfs_ioctl_search_key::max_type"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, max_type) - 60usize];
    ["Offset of field: btrfs_ioctl_search_key::nr_items"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, nr_items) - 64usize];
    ["Offset of field: btrfs_ioctl_search_key::unused"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, unused) - 68usize];
    ["Offset of field: btrfs_ioctl_search_key::unused1"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, unused1) - 72usize];
    ["Offset of field: btrfs_ioctl_search_key::unused2"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, unused2) - 80usize];
    ["Offset of field: btrfs_ioctl_search_key::unused3"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, unused3) - 88usize];
    ["Offset of field: btrfs_ioctl_search_key::unused4"]
        [::std::mem::offset_of!(btrfs_ioctl_search_key, unused4) - 96usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_search_header {
    pub transid: __u64,
    pub objectid: __u64,
    pub offset: __u64,
    pub type_: __u32,
    pub len: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_search_header"]
        [::std::mem::size_of::<btrfs_ioctl_search_header>() - 32usize];
    ["Alignment of btrfs_ioctl_search_header"]
        [::std::mem::align_of::<btrfs_ioctl_search_header>() - 8usize];
    ["Offset of field: btrfs_ioctl_search_header::transid"]
        [::std::mem::offset_of!(btrfs_ioctl_search_header, transid) - 0usize];
    ["Offset of field: btrfs_ioctl_search_header::objectid"]
        [::std::mem::offset_of!(btrfs_ioctl_search_header, objectid) - 8usize];
    ["Offset of field: btrfs_ioctl_search_header::offset"]
        [::std::mem::offset_of!(btrfs_ioctl_search_header, offset) - 16usize];
    ["Offset of field: btrfs_ioctl_search_header::type_"]
        [::std::mem::offset_of!(btrfs_ioctl_search_header, type_) - 24usize];
    ["Offset of field: btrfs_ioctl_search_header::len"]
        [::std::mem::offset_of!(btrfs_ioctl_search_header, len) - 28usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_search_args {
    pub key: btrfs_ioctl_search_key,
    pub buf: [::std::os::raw::c_char; 3992usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_search_args"]
        [::std::mem::size_of::<btrfs_ioctl_search_args>() - 4096usize];
    ["Alignment of btrfs_ioctl_search_args"]
        [::std::mem::align_of::<btrfs_ioctl_search_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_search_args::key"]
        [::std::mem::offset_of!(btrfs_ioctl_search_args, key) - 0usize];
    ["Offset of field: btrfs_ioctl_search_args::buf"]
        [::std::mem::offset_of!(btrfs_ioctl_search_args, buf) - 104usize];
};
#[repr(C)]
#[derive(Debug)]
pub struct btrfs_ioctl_search_args_v2 {
    pub key: btrfs_ioctl_search_key,
    pub buf_size: __u64,
    pub buf: __IncompleteArrayField<__u64>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_search_args_v2"]
        [::std::mem::size_of::<btrfs_ioctl_search_args_v2>() - 112usize];
    ["Alignment of btrfs_ioctl_search_args_v2"]
        [::std::mem::align_of::<btrfs_ioctl_search_args_v2>() - 8usize];
    ["Offset of field: btrfs_ioctl_search_args_v2::key"]
        [::std::mem::offset_of!(btrfs_ioctl_search_args_v2, key) - 0usize];
    ["Offset of field: btrfs_ioctl_search_args_v2::buf_size"]
        [::std::mem::offset_of!(btrfs_ioctl_search_args_v2, buf_size) - 104usize];
    ["Offset of field: btrfs_ioctl_search_args_v2::buf"]
        [::std::mem::offset_of!(btrfs_ioctl_search_args_v2, buf) - 112usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_clone_range_args {
    pub src_fd: __s64,
    pub src_offset: __u64,
    pub src_length: __u64,
    pub dest_offset: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_clone_range_args"]
        [::std::mem::size_of::<btrfs_ioctl_clone_range_args>() - 32usize];
    ["Alignment of btrfs_ioctl_clone_range_args"]
        [::std::mem::align_of::<btrfs_ioctl_clone_range_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_clone_range_args::src_fd"]
        [::std::mem::offset_of!(btrfs_ioctl_clone_range_args, src_fd) - 0usize];
    ["Offset of field: btrfs_ioctl_clone_range_args::src_offset"]
        [::std::mem::offset_of!(btrfs_ioctl_clone_range_args, src_offset) - 8usize];
    ["Offset of field: btrfs_ioctl_clone_range_args::src_length"]
        [::std::mem::offset_of!(btrfs_ioctl_clone_range_args, src_length) - 16usize];
    ["Offset of field: btrfs_ioctl_clone_range_args::dest_offset"]
        [::std::mem::offset_of!(btrfs_ioctl_clone_range_args, dest_offset) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_same_extent_info {
    pub fd: __s64,
    pub logical_offset: __u64,
    pub bytes_deduped: __u64,
    pub status: __s32,
    pub reserved: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_same_extent_info"]
        [::std::mem::size_of::<btrfs_ioctl_same_extent_info>() - 32usize];
    ["Alignment of btrfs_ioctl_same_extent_info"]
        [::std::mem::align_of::<btrfs_ioctl_same_extent_info>() - 8usize];
    ["Offset of field: btrfs_ioctl_same_extent_info::fd"]
        [::std::mem::offset_of!(btrfs_ioctl_same_extent_info, fd) - 0usize];
    ["Offset of field: btrfs_ioctl_same_extent_info::logical_offset"]
        [::std::mem::offset_of!(btrfs_ioctl_same_extent_info, logical_offset) - 8usize];
    ["Offset of field: btrfs_ioctl_same_extent_info::bytes_deduped"]
        [::std::mem::offset_of!(btrfs_ioctl_same_extent_info, bytes_deduped) - 16usize];
    ["Offset of field: btrfs_ioctl_same_extent_info::status"]
        [::std::mem::offset_of!(btrfs_ioctl_same_extent_info, status) - 24usize];
    ["Offset of field: btrfs_ioctl_same_extent_info::reserved"]
        [::std::mem::offset_of!(btrfs_ioctl_same_extent_info, reserved) - 28usize];
};
#[repr(C)]
#[derive(Debug)]
pub struct btrfs_ioctl_same_args {
    pub logical_offset: __u64,
    pub length: __u64,
    pub dest_count: __u16,
    pub reserved1: __u16,
    pub reserved2: __u32,
    pub info: __IncompleteArrayField<btrfs_ioctl_same_extent_info>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_same_args"][::std::mem::size_of::<btrfs_ioctl_same_args>() - 24usize];
    ["Alignment of btrfs_ioctl_same_args"]
        [::std::mem::align_of::<btrfs_ioctl_same_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_same_args::logical_offset"]
        [::std::mem::offset_of!(btrfs_ioctl_same_args, logical_offset) - 0usize];
    ["Offset of field: btrfs_ioctl_same_args::length"]
        [::std::mem::offset_of!(btrfs_ioctl_same_args, length) - 8usize];
    ["Offset of field: btrfs_ioctl_same_args::dest_count"]
        [::std::mem::offset_of!(btrfs_ioctl_same_args, dest_count) - 16usize];
    ["Offset of field: btrfs_ioctl_same_args::reserved1"]
        [::std::mem::offset_of!(btrfs_ioctl_same_args, reserved1) - 18usize];
    ["Offset of field: btrfs_ioctl_same_args::reserved2"]
        [::std::mem::offset_of!(btrfs_ioctl_same_args, reserved2) - 20usize];
    ["Offset of field: btrfs_ioctl_same_args::info"]
        [::std::mem::offset_of!(btrfs_ioctl_same_args, info) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_defrag_range_args {
    pub start: __u64,
    pub len: __u64,
    pub flags: __u64,
    pub extent_thresh: __u32,
    pub compress_type: __u32,
    pub unused: [__u32; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_defrag_range_args"]
        [::std::mem::size_of::<btrfs_ioctl_defrag_range_args>() - 48usize];
    ["Alignment of btrfs_ioctl_defrag_range_args"]
        [::std::mem::align_of::<btrfs_ioctl_defrag_range_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_defrag_range_args::start"]
        [::std::mem::offset_of!(btrfs_ioctl_defrag_range_args, start) - 0usize];
    ["Offset of field: btrfs_ioctl_defrag_range_args::len"]
        [::std::mem::offset_of!(btrfs_ioctl_defrag_range_args, len) - 8usize];
    ["Offset of field: btrfs_ioctl_defrag_range_args::flags"]
        [::std::mem::offset_of!(btrfs_ioctl_defrag_range_args, flags) - 16usize];
    ["Offset of field: btrfs_ioctl_defrag_range_args::extent_thresh"]
        [::std::mem::offset_of!(btrfs_ioctl_defrag_range_args, extent_thresh) - 24usize];
    ["Offset of field: btrfs_ioctl_defrag_range_args::compress_type"]
        [::std::mem::offset_of!(btrfs_ioctl_defrag_range_args, compress_type) - 28usize];
    ["Offset of field: btrfs_ioctl_defrag_range_args::unused"]
        [::std::mem::offset_of!(btrfs_ioctl_defrag_range_args, unused) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_space_info {
    pub flags: __u64,
    pub total_bytes: __u64,
    pub used_bytes: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_space_info"][::std::mem::size_of::<btrfs_ioctl_space_info>() - 24usize];
    ["Alignment of btrfs_ioctl_space_info"]
        [::std::mem::align_of::<btrfs_ioctl_space_info>() - 8usize];
    ["Offset of field: btrfs_ioctl_space_info::flags"]
        [::std::mem::offset_of!(btrfs_ioctl_space_info, flags) - 0usize];
    ["Offset of field: btrfs_ioctl_space_info::total_bytes"]
        [::std::mem::offset_of!(btrfs_ioctl_space_info, total_bytes) - 8usize];
    ["Offset of field: btrfs_ioctl_space_info::used_bytes"]
        [::std::mem::offset_of!(btrfs_ioctl_space_info, used_bytes) - 16usize];
};
#[repr(C)]
#[derive(Debug)]
pub struct btrfs_ioctl_space_args {
    pub space_slots: __u64,
    pub total_spaces: __u64,
    pub spaces: __IncompleteArrayField<btrfs_ioctl_space_info>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_space_args"][::std::mem::size_of::<btrfs_ioctl_space_args>() - 16usize];
    ["Alignment of btrfs_ioctl_space_args"]
        [::std::mem::align_of::<btrfs_ioctl_space_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_space_args::space_slots"]
        [::std::mem::offset_of!(btrfs_ioctl_space_args, space_slots) - 0usize];
    ["Offset of field: btrfs_ioctl_space_args::total_spaces"]
        [::std::mem::offset_of!(btrfs_ioctl_space_args, total_spaces) - 8usize];
    ["Offset of field: btrfs_ioctl_space_args::spaces"]
        [::std::mem::offset_of!(btrfs_ioctl_space_args, spaces) - 16usize];
};
#[repr(C)]
#[derive(Debug)]
pub struct btrfs_data_container {
    pub bytes_left: __u32,
    pub bytes_missing: __u32,
    pub elem_cnt: __u32,
    pub elem_missed: __u32,
    pub val: __IncompleteArrayField<__u64>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_data_container"][::std::mem::size_of::<btrfs_data_container>() - 16usize];
    ["Alignment of btrfs_data_container"][::std::mem::align_of::<btrfs_data_container>() - 8usize];
    ["Offset of field: btrfs_data_container::bytes_left"]
        [::std::mem::offset_of!(btrfs_data_container, bytes_left) - 0usize];
    ["Offset of field: btrfs_data_container::bytes_missing"]
        [::std::mem::offset_of!(btrfs_data_container, bytes_missing) - 4usize];
    ["Offset of field: btrfs_data_container::elem_cnt"]
        [::std::mem::offset_of!(btrfs_data_container, elem_cnt) - 8usize];
    ["Offset of field: btrfs_data_container::elem_missed"]
        [::std::mem::offset_of!(btrfs_data_container, elem_missed) - 12usize];
    ["Offset of field: btrfs_data_container::val"]
        [::std::mem::offset_of!(btrfs_data_container, val) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_ino_path_args {
    pub inum: __u64,
    pub size: __u64,
    pub reserved: [__u64; 4usize],
    pub fspath: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_ino_path_args"]
        [::std::mem::size_of::<btrfs_ioctl_ino_path_args>() - 56usize];
    ["Alignment of btrfs_ioctl_ino_path_args"]
        [::std::mem::align_of::<btrfs_ioctl_ino_path_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_ino_path_args::inum"]
        [::std::mem::offset_of!(btrfs_ioctl_ino_path_args, inum) - 0usize];
    ["Offset of field: btrfs_ioctl_ino_path_args::size"]
        [::std::mem::offset_of!(btrfs_ioctl_ino_path_args, size) - 8usize];
    ["Offset of field: btrfs_ioctl_ino_path_args::reserved"]
        [::std::mem::offset_of!(btrfs_ioctl_ino_path_args, reserved) - 16usize];
    ["Offset of field: btrfs_ioctl_ino_path_args::fspath"]
        [::std::mem::offset_of!(btrfs_ioctl_ino_path_args, fspath) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_logical_ino_args {
    pub logical: __u64,
    pub size: __u64,
    pub reserved: [__u64; 3usize],
    pub flags: __u64,
    pub inodes: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_logical_ino_args"]
        [::std::mem::size_of::<btrfs_ioctl_logical_ino_args>() - 56usize];
    ["Alignment of btrfs_ioctl_logical_ino_args"]
        [::std::mem::align_of::<btrfs_ioctl_logical_ino_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_logical_ino_args::logical"]
        [::std::mem::offset_of!(btrfs_ioctl_logical_ino_args, logical) - 0usize];
    ["Offset of field: btrfs_ioctl_logical_ino_args::size"]
        [::std::mem::offset_of!(btrfs_ioctl_logical_ino_args, size) - 8usize];
    ["Offset of field: btrfs_ioctl_logical_ino_args::reserved"]
        [::std::mem::offset_of!(btrfs_ioctl_logical_ino_args, reserved) - 16usize];
    ["Offset of field: btrfs_ioctl_logical_ino_args::flags"]
        [::std::mem::offset_of!(btrfs_ioctl_logical_ino_args, flags) - 40usize];
    ["Offset of field: btrfs_ioctl_logical_ino_args::inodes"]
        [::std::mem::offset_of!(btrfs_ioctl_logical_ino_args, inodes) - 48usize];
};
pub const btrfs_dev_stat_values_BTRFS_DEV_STAT_WRITE_ERRS: btrfs_dev_stat_values = 0;
pub const btrfs_dev_stat_values_BTRFS_DEV_STAT_READ_ERRS: btrfs_dev_stat_values = 1;
pub const btrfs_dev_stat_values_BTRFS_DEV_STAT_FLUSH_ERRS: btrfs_dev_stat_values = 2;
pub const btrfs_dev_stat_values_BTRFS_DEV_STAT_CORRUPTION_ERRS: btrfs_dev_stat_values = 3;
pub const btrfs_dev_stat_values_BTRFS_DEV_STAT_GENERATION_ERRS: btrfs_dev_stat_values = 4;
pub const btrfs_dev_stat_values_BTRFS_DEV_STAT_VALUES_MAX: btrfs_dev_stat_values = 5;
pub type btrfs_dev_stat_values = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_get_dev_stats {
    pub devid: __u64,
    pub nr_items: __u64,
    pub flags: __u64,
    pub values: [__u64; 5usize],
    pub unused: [__u64; 121usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_get_dev_stats"]
        [::std::mem::size_of::<btrfs_ioctl_get_dev_stats>() - 1032usize];
    ["Alignment of btrfs_ioctl_get_dev_stats"]
        [::std::mem::align_of::<btrfs_ioctl_get_dev_stats>() - 8usize];
    ["Offset of field: btrfs_ioctl_get_dev_stats::devid"]
        [::std::mem::offset_of!(btrfs_ioctl_get_dev_stats, devid) - 0usize];
    ["Offset of field: btrfs_ioctl_get_dev_stats::nr_items"]
        [::std::mem::offset_of!(btrfs_ioctl_get_dev_stats, nr_items) - 8usize];
    ["Offset of field: btrfs_ioctl_get_dev_stats::flags"]
        [::std::mem::offset_of!(btrfs_ioctl_get_dev_stats, flags) - 16usize];
    ["Offset of field: btrfs_ioctl_get_dev_stats::values"]
        [::std::mem::offset_of!(btrfs_ioctl_get_dev_stats, values) - 24usize];
    ["Offset of field: btrfs_ioctl_get_dev_stats::unused"]
        [::std::mem::offset_of!(btrfs_ioctl_get_dev_stats, unused) - 64usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_quota_ctl_args {
    pub cmd: __u64,
    pub status: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_quota_ctl_args"]
        [::std::mem::size_of::<btrfs_ioctl_quota_ctl_args>() - 16usize];
    ["Alignment of btrfs_ioctl_quota_ctl_args"]
        [::std::mem::align_of::<btrfs_ioctl_quota_ctl_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_quota_ctl_args::cmd"]
        [::std::mem::offset_of!(btrfs_ioctl_quota_ctl_args, cmd) - 0usize];
    ["Offset of field: btrfs_ioctl_quota_ctl_args::status"]
        [::std::mem::offset_of!(btrfs_ioctl_quota_ctl_args, status) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_quota_rescan_args {
    pub flags: __u64,
    pub progress: __u64,
    pub reserved: [__u64; 6usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_quota_rescan_args"]
        [::std::mem::size_of::<btrfs_ioctl_quota_rescan_args>() - 64usize];
    ["Alignment of btrfs_ioctl_quota_rescan_args"]
        [::std::mem::align_of::<btrfs_ioctl_quota_rescan_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_quota_rescan_args::flags"]
        [::std::mem::offset_of!(btrfs_ioctl_quota_rescan_args, flags) - 0usize];
    ["Offset of field: btrfs_ioctl_quota_rescan_args::progress"]
        [::std::mem::offset_of!(btrfs_ioctl_quota_rescan_args, progress) - 8usize];
    ["Offset of field: btrfs_ioctl_quota_rescan_args::reserved"]
        [::std::mem::offset_of!(btrfs_ioctl_quota_rescan_args, reserved) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_qgroup_assign_args {
    pub assign: __u64,
    pub src: __u64,
    pub dst: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_qgroup_assign_args"]
        [::std::mem::size_of::<btrfs_ioctl_qgroup_assign_args>() - 24usize];
    ["Alignment of btrfs_ioctl_qgroup_assign_args"]
        [::std::mem::align_of::<btrfs_ioctl_qgroup_assign_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_qgroup_assign_args::assign"]
        [::std::mem::offset_of!(btrfs_ioctl_qgroup_assign_args, assign) - 0usize];
    ["Offset of field: btrfs_ioctl_qgroup_assign_args::src"]
        [::std::mem::offset_of!(btrfs_ioctl_qgroup_assign_args, src) - 8usize];
    ["Offset of field: btrfs_ioctl_qgroup_assign_args::dst"]
        [::std::mem::offset_of!(btrfs_ioctl_qgroup_assign_args, dst) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_qgroup_create_args {
    pub create: __u64,
    pub qgroupid: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_qgroup_create_args"]
        [::std::mem::size_of::<btrfs_ioctl_qgroup_create_args>() - 16usize];
    ["Alignment of btrfs_ioctl_qgroup_create_args"]
        [::std::mem::align_of::<btrfs_ioctl_qgroup_create_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_qgroup_create_args::create"]
        [::std::mem::offset_of!(btrfs_ioctl_qgroup_create_args, create) - 0usize];
    ["Offset of field: btrfs_ioctl_qgroup_create_args::qgroupid"]
        [::std::mem::offset_of!(btrfs_ioctl_qgroup_create_args, qgroupid) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_timespec {
    pub sec: __u64,
    pub nsec: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_timespec"][::std::mem::size_of::<btrfs_ioctl_timespec>() - 16usize];
    ["Alignment of btrfs_ioctl_timespec"][::std::mem::align_of::<btrfs_ioctl_timespec>() - 8usize];
    ["Offset of field: btrfs_ioctl_timespec::sec"]
        [::std::mem::offset_of!(btrfs_ioctl_timespec, sec) - 0usize];
    ["Offset of field: btrfs_ioctl_timespec::nsec"]
        [::std::mem::offset_of!(btrfs_ioctl_timespec, nsec) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_received_subvol_args {
    pub uuid: [::std::os::raw::c_char; 16usize],
    pub stransid: __u64,
    pub rtransid: __u64,
    pub stime: btrfs_ioctl_timespec,
    pub rtime: btrfs_ioctl_timespec,
    pub flags: __u64,
    pub reserved: [__u64; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_received_subvol_args"]
        [::std::mem::size_of::<btrfs_ioctl_received_subvol_args>() - 200usize];
    ["Alignment of btrfs_ioctl_received_subvol_args"]
        [::std::mem::align_of::<btrfs_ioctl_received_subvol_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_received_subvol_args::uuid"]
        [::std::mem::offset_of!(btrfs_ioctl_received_subvol_args, uuid) - 0usize];
    ["Offset of field: btrfs_ioctl_received_subvol_args::stransid"]
        [::std::mem::offset_of!(btrfs_ioctl_received_subvol_args, stransid) - 16usize];
    ["Offset of field: btrfs_ioctl_received_subvol_args::rtransid"]
        [::std::mem::offset_of!(btrfs_ioctl_received_subvol_args, rtransid) - 24usize];
    ["Offset of field: btrfs_ioctl_received_subvol_args::stime"]
        [::std::mem::offset_of!(btrfs_ioctl_received_subvol_args, stime) - 32usize];
    ["Offset of field: btrfs_ioctl_received_subvol_args::rtime"]
        [::std::mem::offset_of!(btrfs_ioctl_received_subvol_args, rtime) - 48usize];
    ["Offset of field: btrfs_ioctl_received_subvol_args::flags"]
        [::std::mem::offset_of!(btrfs_ioctl_received_subvol_args, flags) - 64usize];
    ["Offset of field: btrfs_ioctl_received_subvol_args::reserved"]
        [::std::mem::offset_of!(btrfs_ioctl_received_subvol_args, reserved) - 72usize];
};
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_timespec_32 {
    pub sec: __u64,
    pub nsec: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_timespec_32"][::std::mem::size_of::<btrfs_ioctl_timespec_32>() - 12usize];
    ["Alignment of btrfs_ioctl_timespec_32"]
        [::std::mem::align_of::<btrfs_ioctl_timespec_32>() - 1usize];
    ["Offset of field: btrfs_ioctl_timespec_32::sec"]
        [::std::mem::offset_of!(btrfs_ioctl_timespec_32, sec) - 0usize];
    ["Offset of field: btrfs_ioctl_timespec_32::nsec"]
        [::std::mem::offset_of!(btrfs_ioctl_timespec_32, nsec) - 8usize];
};
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_received_subvol_args_32 {
    pub uuid: [::std::os::raw::c_char; 16usize],
    pub stransid: __u64,
    pub rtransid: __u64,
    pub stime: btrfs_ioctl_timespec_32,
    pub rtime: btrfs_ioctl_timespec_32,
    pub flags: __u64,
    pub reserved: [__u64; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_received_subvol_args_32"]
        [::std::mem::size_of::<btrfs_ioctl_received_subvol_args_32>() - 192usize];
    ["Alignment of btrfs_ioctl_received_subvol_args_32"]
        [::std::mem::align_of::<btrfs_ioctl_received_subvol_args_32>() - 1usize];
    ["Offset of field: btrfs_ioctl_received_subvol_args_32::uuid"]
        [::std::mem::offset_of!(btrfs_ioctl_received_subvol_args_32, uuid) - 0usize];
    ["Offset of field: btrfs_ioctl_received_subvol_args_32::stransid"]
        [::std::mem::offset_of!(btrfs_ioctl_received_subvol_args_32, stransid) - 16usize];
    ["Offset of field: btrfs_ioctl_received_subvol_args_32::rtransid"]
        [::std::mem::offset_of!(btrfs_ioctl_received_subvol_args_32, rtransid) - 24usize];
    ["Offset of field: btrfs_ioctl_received_subvol_args_32::stime"]
        [::std::mem::offset_of!(btrfs_ioctl_received_subvol_args_32, stime) - 32usize];
    ["Offset of field: btrfs_ioctl_received_subvol_args_32::rtime"]
        [::std::mem::offset_of!(btrfs_ioctl_received_subvol_args_32, rtime) - 44usize];
    ["Offset of field: btrfs_ioctl_received_subvol_args_32::flags"]
        [::std::mem::offset_of!(btrfs_ioctl_received_subvol_args_32, flags) - 56usize];
    ["Offset of field: btrfs_ioctl_received_subvol_args_32::reserved"]
        [::std::mem::offset_of!(btrfs_ioctl_received_subvol_args_32, reserved) - 64usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_send_args {
    pub send_fd: __s64,
    pub clone_sources_count: __u64,
    pub clone_sources: *mut __u64,
    pub parent_root: __u64,
    pub flags: __u64,
    pub version: __u32,
    pub reserved: [__u8; 28usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_send_args"][::std::mem::size_of::<btrfs_ioctl_send_args>() - 72usize];
    ["Alignment of btrfs_ioctl_send_args"]
        [::std::mem::align_of::<btrfs_ioctl_send_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_send_args::send_fd"]
        [::std::mem::offset_of!(btrfs_ioctl_send_args, send_fd) - 0usize];
    ["Offset of field: btrfs_ioctl_send_args::clone_sources_count"]
        [::std::mem::offset_of!(btrfs_ioctl_send_args, clone_sources_count) - 8usize];
    ["Offset of field: btrfs_ioctl_send_args::clone_sources"]
        [::std::mem::offset_of!(btrfs_ioctl_send_args, clone_sources) - 16usize];
    ["Offset of field: btrfs_ioctl_send_args::parent_root"]
        [::std::mem::offset_of!(btrfs_ioctl_send_args, parent_root) - 24usize];
    ["Offset of field: btrfs_ioctl_send_args::flags"]
        [::std::mem::offset_of!(btrfs_ioctl_send_args, flags) - 32usize];
    ["Offset of field: btrfs_ioctl_send_args::version"]
        [::std::mem::offset_of!(btrfs_ioctl_send_args, version) - 40usize];
    ["Offset of field: btrfs_ioctl_send_args::reserved"]
        [::std::mem::offset_of!(btrfs_ioctl_send_args, reserved) - 44usize];
};
#[repr(C, packed)]
#[derive(Copy, Clone)]
pub struct btrfs_ioctl_send_args_64 {
    pub send_fd: __s64,
    pub clone_sources_count: __u64,
    pub __bindgen_anon_1: btrfs_ioctl_send_args_64__bindgen_ty_1,
    pub parent_root: __u64,
    pub flags: __u64,
    pub reserved: [__u64; 4usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union btrfs_ioctl_send_args_64__bindgen_ty_1 {
    pub clone_sources: *mut __u64,
    pub __clone_sources_alignment: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_send_args_64__bindgen_ty_1"]
        [::std::mem::size_of::<btrfs_ioctl_send_args_64__bindgen_ty_1>() - 8usize];
    ["Alignment of btrfs_ioctl_send_args_64__bindgen_ty_1"]
        [::std::mem::align_of::<btrfs_ioctl_send_args_64__bindgen_ty_1>() - 8usize];
    ["Offset of field: btrfs_ioctl_send_args_64__bindgen_ty_1::clone_sources"]
        [::std::mem::offset_of!(btrfs_ioctl_send_args_64__bindgen_ty_1, clone_sources) - 0usize];
    ["Offset of field: btrfs_ioctl_send_args_64__bindgen_ty_1::__clone_sources_alignment"][::std::mem::offset_of!(
        btrfs_ioctl_send_args_64__bindgen_ty_1,
        __clone_sources_alignment
    )
        - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_send_args_64"]
        [::std::mem::size_of::<btrfs_ioctl_send_args_64>() - 72usize];
    ["Alignment of btrfs_ioctl_send_args_64"]
        [::std::mem::align_of::<btrfs_ioctl_send_args_64>() - 1usize];
    ["Offset of field: btrfs_ioctl_send_args_64::send_fd"]
        [::std::mem::offset_of!(btrfs_ioctl_send_args_64, send_fd) - 0usize];
    ["Offset of field: btrfs_ioctl_send_args_64::clone_sources_count"]
        [::std::mem::offset_of!(btrfs_ioctl_send_args_64, clone_sources_count) - 8usize];
    ["Offset of field: btrfs_ioctl_send_args_64::parent_root"]
        [::std::mem::offset_of!(btrfs_ioctl_send_args_64, parent_root) - 24usize];
    ["Offset of field: btrfs_ioctl_send_args_64::flags"]
        [::std::mem::offset_of!(btrfs_ioctl_send_args_64, flags) - 32usize];
    ["Offset of field: btrfs_ioctl_send_args_64::reserved"]
        [::std::mem::offset_of!(btrfs_ioctl_send_args_64, reserved) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_get_subvol_info_args {
    pub treeid: __u64,
    pub name: [::std::os::raw::c_char; 256usize],
    pub parent_id: __u64,
    pub dirid: __u64,
    pub generation: __u64,
    pub flags: __u64,
    pub uuid: [__u8; 16usize],
    pub parent_uuid: [__u8; 16usize],
    pub received_uuid: [__u8; 16usize],
    pub ctransid: __u64,
    pub otransid: __u64,
    pub stransid: __u64,
    pub rtransid: __u64,
    pub ctime: btrfs_ioctl_timespec,
    pub otime: btrfs_ioctl_timespec,
    pub stime: btrfs_ioctl_timespec,
    pub rtime: btrfs_ioctl_timespec,
    pub reserved: [__u64; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_get_subvol_info_args"]
        [::std::mem::size_of::<btrfs_ioctl_get_subvol_info_args>() - 504usize];
    ["Alignment of btrfs_ioctl_get_subvol_info_args"]
        [::std::mem::align_of::<btrfs_ioctl_get_subvol_info_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::treeid"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, treeid) - 0usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::name"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, name) - 8usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::parent_id"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, parent_id) - 264usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::dirid"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, dirid) - 272usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::generation"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, generation) - 280usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::flags"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, flags) - 288usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::uuid"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, uuid) - 296usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::parent_uuid"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, parent_uuid) - 312usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::received_uuid"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, received_uuid) - 328usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::ctransid"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, ctransid) - 344usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::otransid"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, otransid) - 352usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::stransid"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, stransid) - 360usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::rtransid"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, rtransid) - 368usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::ctime"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, ctime) - 376usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::otime"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, otime) - 392usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::stime"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, stime) - 408usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::rtime"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, rtime) - 424usize];
    ["Offset of field: btrfs_ioctl_get_subvol_info_args::reserved"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_info_args, reserved) - 440usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_get_subvol_rootref_args {
    pub min_treeid: __u64,
    pub rootref: [btrfs_ioctl_get_subvol_rootref_args__bindgen_ty_1; 255usize],
    pub num_items: __u8,
    pub align: [__u8; 7usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_get_subvol_rootref_args__bindgen_ty_1 {
    pub treeid: __u64,
    pub dirid: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_get_subvol_rootref_args__bindgen_ty_1"]
        [::std::mem::size_of::<btrfs_ioctl_get_subvol_rootref_args__bindgen_ty_1>() - 16usize];
    ["Alignment of btrfs_ioctl_get_subvol_rootref_args__bindgen_ty_1"]
        [::std::mem::align_of::<btrfs_ioctl_get_subvol_rootref_args__bindgen_ty_1>() - 8usize];
    ["Offset of field: btrfs_ioctl_get_subvol_rootref_args__bindgen_ty_1::treeid"][::std::mem::offset_of!(
        btrfs_ioctl_get_subvol_rootref_args__bindgen_ty_1,
        treeid
    ) - 0usize];
    ["Offset of field: btrfs_ioctl_get_subvol_rootref_args__bindgen_ty_1::dirid"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_rootref_args__bindgen_ty_1, dirid) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_get_subvol_rootref_args"]
        [::std::mem::size_of::<btrfs_ioctl_get_subvol_rootref_args>() - 4096usize];
    ["Alignment of btrfs_ioctl_get_subvol_rootref_args"]
        [::std::mem::align_of::<btrfs_ioctl_get_subvol_rootref_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_get_subvol_rootref_args::min_treeid"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_rootref_args, min_treeid) - 0usize];
    ["Offset of field: btrfs_ioctl_get_subvol_rootref_args::rootref"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_rootref_args, rootref) - 8usize];
    ["Offset of field: btrfs_ioctl_get_subvol_rootref_args::num_items"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_rootref_args, num_items) - 4088usize];
    ["Offset of field: btrfs_ioctl_get_subvol_rootref_args::align"]
        [::std::mem::offset_of!(btrfs_ioctl_get_subvol_rootref_args, align) - 4089usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct btrfs_ioctl_encoded_io_args {
    pub iov: *mut iovec,
    pub iovcnt: ::std::os::raw::c_ulong,
    pub offset: __s64,
    pub flags: __u64,
    pub len: __u64,
    pub unencoded_len: __u64,
    pub unencoded_offset: __u64,
    pub compression: __u32,
    pub encryption: __u32,
    pub reserved: [__u8; 64usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of btrfs_ioctl_encoded_io_args"]
        [::std::mem::size_of::<btrfs_ioctl_encoded_io_args>() - 128usize];
    ["Alignment of btrfs_ioctl_encoded_io_args"]
        [::std::mem::align_of::<btrfs_ioctl_encoded_io_args>() - 8usize];
    ["Offset of field: btrfs_ioctl_encoded_io_args::iov"]
        [::std::mem::offset_of!(btrfs_ioctl_encoded_io_args, iov) - 0usize];
    ["Offset of field: btrfs_ioctl_encoded_io_args::iovcnt"]
        [::std::mem::offset_of!(btrfs_ioctl_encoded_io_args, iovcnt) - 8usize];
    ["Offset of field: btrfs_ioctl_encoded_io_args::offset"]
        [::std::mem::offset_of!(btrfs_ioctl_encoded_io_args, offset) - 16usize];
    ["Offset of field: btrfs_ioctl_encoded_io_args::flags"]
        [::std::mem::offset_of!(btrfs_ioctl_encoded_io_args, flags) - 24usize];
    ["Offset of field: btrfs_ioctl_encoded_io_args::len"]
        [::std::mem::offset_of!(btrfs_ioctl_encoded_io_args, len) - 32usize];
    ["Offset of field: btrfs_ioctl_encoded_io_args::unencoded_len"]
        [::std::mem::offset_of!(btrfs_ioctl_encoded_io_args, unencoded_len) - 40usize];
    ["Offset of field: btrfs_ioctl_encoded_io_args::unencoded_offset"]
        [::std::mem::offset_of!(btrfs_ioctl_encoded_io_args, unencoded_offset) - 48usize];
    ["Offset of field: btrfs_ioctl_encoded_io_args::compression"]
        [::std::mem::offset_of!(btrfs_ioctl_encoded_io_args, compression) - 56usize];
    ["Offset of field: btrfs_ioctl_encoded_io_args::encryption"]
        [::std::mem::offset_of!(btrfs_ioctl_encoded_io_args, encryption) - 60usize];
    ["Offset of field: btrfs_ioctl_encoded_io_args::reserved"]
        [::std::mem::offset_of!(btrfs_ioctl_encoded_io_args, reserved) - 64usize];
};
pub const btrfs_err_code_notused: btrfs_err_code = 0;
pub const btrfs_err_code_BTRFS_ERROR_DEV_RAID1_MIN_NOT_MET: btrfs_err_code = 1;
pub const btrfs_err_code_BTRFS_ERROR_DEV_RAID10_MIN_NOT_MET: btrfs_err_code = 2;
pub const btrfs_err_code_BTRFS_ERROR_DEV_RAID5_MIN_NOT_MET: btrfs_err_code = 3;
pub const btrfs_err_code_BTRFS_ERROR_DEV_RAID6_MIN_NOT_MET: btrfs_err_code = 4;
pub const btrfs_err_code_BTRFS_ERROR_DEV_TGT_REPLACE: btrfs_err_code = 5;
pub const btrfs_err_code_BTRFS_ERROR_DEV_MISSING_NOT_FOUND: btrfs_err_code = 6;
pub const btrfs_err_code_BTRFS_ERROR_DEV_ONLY_WRITABLE: btrfs_err_code = 7;
pub const btrfs_err_code_BTRFS_ERROR_DEV_EXCL_RUN_IN_PROGRESS: btrfs_err_code = 8;
pub const btrfs_err_code_BTRFS_ERROR_DEV_RAID1C3_MIN_NOT_MET: btrfs_err_code = 9;
pub const btrfs_err_code_BTRFS_ERROR_DEV_RAID1C4_MIN_NOT_MET: btrfs_err_code = 10;
pub type btrfs_err_code = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iovec {
    pub _address: u8,
}
