/* automatically generated by rust-bindgen 0.70.1 */

pub const __GENTOO_NOT_FREESTANDING: u32 = 1;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const BTRFS_LIB_MAJOR: u32 = 0;
pub const BTRFS_LIB_MINOR: u32 = 1;
pub const BTRFS_LIB_PATCHLEVEL: u32 = 4;
pub const BTRFS_LIB_VERSION: u32 = 104;
pub const BTRFS_BUILD_VERSION: &[u8; 12] = b"Btrfs v6.11\0";
